name: macOS Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install build tools
        run: |
          brew install ninja cmake

      - name: Setup vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/vcpkg
            vcpkg_installed
            vcpkg
          key: vcpkg-macos-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-macos-

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.*'
          arch: clang_64
          tools: 'tools_ninja'
          cache: true

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'f5ec6f30ff70f04f841436a0f36600bdbabfcfbf'
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true

      - name: Configure
        env:
          Qt6_DIR: ${{ env.Qt6_DIR }}
        run: |
          cmake --preset macos

      - name: Build
        run: |
          cmake --build --preset macos-release

      - name: Package
        run: |
          cd build
          cpack -C Release -V
          ls -la *.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QT_Template-macOS-arm64
          path: build/*.dmg
          if-no-files-found: error