name: Windows Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Setup vcpkg cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/vcpkg
            vcpkg_installed
            vcpkg
          key: vcpkg-windows-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            vcpkg-windows-

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.*'
          arch: win64_msvc2022_64
          tools: 'tools_ninja tools_vcredist'
          cache: true

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'f5ec6f30ff70f04f841436a0f36600bdbabfcfbf'
          vcpkgJsonGlob: 'vcpkg.json'
          runVcpkgInstall: true

      - name: Configure
        env:
          QT_MSVC_DIR: ${{ env.Qt6_DIR }}
        run: cmake --preset windows-msvc

      - name: Build
        run: cmake --build --preset msvc-release

      - name: Package
        run: |
          cd build
          cpack -C Release -V
          dir *.exe *.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: QT_Template-windows
          path: |
            build/*.exe
            build/*.zip
          if-no-files-found: error  # 如果没有找到文件则报错
